kind: Service
apiVersion: v1
metadata:
  name: docker-magento
  labels:
    app: docker-magento
spec:
  type: NodePort
  selector:
    app: docker-magento
  ports:
  - name: http
    port: 80
    targetPort: http
